### ISSUE TITLE
Allow for configurable sample rate

### ISSUE THREAD

**Issue by joelcomp1** [ThomasHabets/gr-habets38#1]
I added the ability to remove the hardcoded 8000000 sample rate and can now be passed in via the GNU Radio block as a input to match up with the other components. I can submit a pull request for the changes if you want or provide you the deltas (not that many)

**Comment by ThomasHabets** [comment]
Pull request would be best, thanks!

**Comment by joelcomp1** [comment]
ok sounds good!  I think you may have to give me permission to create/push a branch.

**Comment by ThomasHabets** [comment]
I shouldn't need to. The normal flow is that you fork the repo on github, and then via github's web UI click to create a PR against my repo.

**Comment by joelcomp1** [comment]
ah yes my bad, done.

**Comment by ThomasHabets** [comment]
Merged. Thanks.
